config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # # see all the restaurants
  # get '/restaurants', to: "restaurants#index"

  # # see one restaurant
  # get '/restaurants/:id', to: "restaurants#show"

  # # create a restaurant
  #   # display the form
  # get '/restaurants/new', to: "restaurants#new", as: :new_restaurant
  #   # post information into DB
  # post '/restaurants', to: "restaurants#create"

  # # update a restaurant
  #   # display the form
  # get '/restaurants/:id/edit', to: "restaurants#edit"
  #   # post information into db
  # patch '/restaurants/:id', to: "restaurants#update"

  # # destroy a restaurant
  # delete '/restaurants/:id', to: "restaurants#destroy"
  resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :rating, inclusion: { in: 1..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  # get '/restaurants/:id', to: "restaurants#show"
  def show
  end

  # display the form
  def new
    @restaurant = Restaurant.new
  end

  # pots information into DB
  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord549</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div>
  <%= form_for(restaurant) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :address %>
    <%= f.text_field :address %>
    <%= f.label :rating %>
    <%= f.number_field :rating %>
    <%= f.submit %>
  <% end %>
</div>

app/views/restaurants/edit.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>All my restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
  <li>
    <h5><%= restaurant.name %><%= '*' * restaurant.rating %><h5>
    <p><%= restaurant.address %> </p>
    <%= link_to "See more", restaurant_path(restaurant) %>
  </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>

<!-- params {
  restaurant {
    name: 'hee',
    address: 'jvfj',
    rating: 5
  }
}

Restaurant.new(params[:restaurant])
 -->

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %><%= '*' * @restaurant.rating %> </h1>
<h2><%= @restaurant.address %> </h2>
<%= link_to "edit restaurant", edit_restaurant_path(@restaurant)  %>
<%= link_to 'destroy', restaurant_path(@restaurant), method: :delete, data: {confirm: "Are you sure?"} %>